"""Add name and email to Doctor

Revision ID: 258d36098893
Revises: 7c91064c27ca
Create Date: 2025-07-23 22:40:57.202244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258d36098893'
down_revision = '7c91064c27ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
