"""Add patient_name to Appointment

Revision ID: 7c91064c27ca
Revises: 0699be7aa06b
Create Date: 2025-07-23 16:40:42.736233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c91064c27ca'
down_revision = '0699be7aa06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
